random_seed: 42

datasets:
  - california_housing
  #- bemtpl16

models:
  Intercept:
    variants:
      intercept:

  GBM:
    variants:
      gbm:
        learning_rate: 0.1
        max_depth: 3
        min_samples_leaf: 20
        k_folds: 5
        max_estimators: 2500 

  CCPPTree:
    variants:
      p_10:
        significance_level: 0.10
        min_samples_leaf: 20
        max_depth: 15
      p_05:
        significance_level: 0.05
        min_samples_leaf: 20
        max_depth: 15
      p_01:
        significance_level: 0.01
        min_samples_leaf: 20
        max_depth: 15

  DoubleRegression:
    variants:
      gbm_ccp05:
        ordering_regressor_params:
          learning_rate: 0.1
          max_depth: 3
          min_samples_leaf: 20
          k_folds: 5
          max_estimators: 2500 
        prediction_regressor_params:
          significance_level: 0.05
          min_samples_leaf: 20
          max_depth: 15


  #CCPPTreeBoosting:
  #  variants:
  #    pboosting_inf:
  #      learning_rate: 0.1
  #      significance_level: 1000000000.0
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
  #    pboosting_10:
  #      learning_rate: 0.1
  #      significance_level: 0.1
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
  #    pboosting_05:
  #      learning_rate: 0.1
  #      significance_level: 0.05
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
  #    pboosting_01:
  #      learning_rate: 0.1
  #      significance_level: 0.01
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500

  #RecursivePTreeBoosting:
  #  variants:
  #    rboost_10:
  #      learning_rate: 0.1
  #      threshold: 0.1
  #      prune_if: ">="
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
  #    rboost_05:
  #      learning_rate: 0.1
  #      threshold: 0.05
  #      prune_if: ">="
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
  #    rboost_01:
  #      learning_rate: 0.1
  #      threshold: 0.01
  #      prune_if: ">="
  #      min_samples_leaf: 20
  #      max_depth: 3
  #      max_estimators: 2500
