random_seed: 42

datasets:
  - california
  - bemtpl16

models:
  GBM:
    variants:
      gbm:
        learning_rate: 0.1
        max_depth: 3
        min_samples_leaf: 20
        k_folds: 5           # set to 1 to disable CV
        max_estimators: 200

  CCPPTreeBoosting:
    variants:
      pboosting_inf:
        learning_rate: 0.1
        significance_level: 1000000000.0
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
      pboosting_10:
        learning_rate: 0.1
        significance_level: 0.1
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
      pboosting_05:
        learning_rate: 0.1
        significance_level: 0.05
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
      pboosting_01:
        learning_rate: 0.1
        significance_level: 0.01
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200

  RecursivePTreeBoosting:
    variants:
      rboost_10:
        learning_rate: 0.1
        threshold: 0.1
        prune_if: ">="
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
      rboost_05:
        learning_rate: 0.1
        threshold: 0.05
        prune_if: ">="
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
      rboost_01:
        learning_rate: 0.1
        threshold: 0.01
        prune_if: ">="
        min_samples_leaf: 20
        max_depth: 3
        max_estimators: 200
